# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20171114_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
